name: first test on AWS

on:
  push:
    branches:
      - main


jobs:
  
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout              #checkout means make a copy of the code from the repo
        uses: actions/checkout@v4  # some of the inbuilt functions, provided by github for doing some common tasks.   

      - name: Install Python-3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3 # this action logins to dockerhub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image and push to DockerHub
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: maverickmindset10/first-action:latest
